[package]
name = "twumc_backend"
version = "1.0.0"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
diesel = { version = "1.4.8", features = ["postgres"] }
dotenv = "0.15.0"
bcrypt = "0.10.1"
jwt = "0.15.0"
hmac = "0.11.0"
sha2 = "0.9.8"
json = "0.12.4"
